on:
  workflow_dispatch:
    inputs:
      typeId:
        description: "Le Type de vidéo"
        required: true
        default: "1"
      thumbnail:
        description: "Une URL vers la miniature de la vidéo"
        required: true
        default: "https://www.stored-youtube-video-thumbnails.ggio.fr/258"
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: sudo apt install apt install -y libnss3 libdbus-1-3 libatk1.0-0 libasound2 libxrandr2 libxkbcommon-dev libxfixes3 libxcomposite1 libxdamage1 libgbm-dev libatk-bridge2.0-0
      - run: npm i
      - run: echo $WORKFLOW_INPUT > props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build -- --props="./props.json"
      - uses: actions/upload-artifact@v3
        with:
          name: out.mp4
          path: out.mp4
